name: Setup repository for CI tests
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: .tool-versions
        cache: yarn
    - run: yarn --immutable --immutable-cache --check-cache
      shell: bash
