name: Docker
on:
  pull_request:
  merge_group:
env:
  PR_NUMBER: ${{ github.event.number }}
jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the serlo-org-database-layer image
        uses: docker/build-push-action@v5
        with:
          push: false
          file: ./Dockerfile
          tags: serlo-org-database-layer:PR-${{ env.PR_NUMBER }}
