name: Pacts
on:
  pull_request:
  merge_group:
jobs:
  pacts_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: serlo/configure-repositories/actions/setup-mysql@main
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: ./.github/wait-for-mysql.sh
      - run: cargo run &
      - run: yarn pacts
